// emberc.em - 自托管 Ember 编译器：读 input.em，向 stdout 发射 ARM64 汇编
// Project Basilisk 第四阶段试金石 7：Ember 写的代码生成器
// 用法：./emberc > output.s && as + ld（与种子产物同构：栈机模型/svc 内联/bl FFI）
//
// 设计裁决：
//   1. 输出走 stdout 重定向（免 3 参 open 与 mode 位），print 基建全复用
//   2. 帧大小定死 128B（16 槽 x 8B）：单遍流式编译，函数头 sub sp 先于 body 发射
//   3. 表达式不建树：codegen 天然后缀序（lhs->push->rhs->pop->op），流式直出
//   4. 发射片段长度由 slen() 运行时数 \0，零手数
// 槽 i（1-based）地址 = [x29, #-(i*8)]；表达式压弹 16B 保持 sp 对齐
// 三表合一块 tbl：vtab@+0（2B 条目=sym）etab@+256（4B=sym+kind）stab@+1024（2B=sym）
// extern kind：0=bl  1/3/4/5/6=exit/read/write/open/close svc 号  197/73=mmap/munmap
//   4097=load8  4098=store8  4099=load64  4100=store64  4101=load32

extern fn open(path: i32, flags: i32) -> i32;
extern fn read(fd: i32, buf: i32, len: i32) -> i32;
extern fn write(fd: i32, buf: i32, len: i32) -> i32;
extern fn close(fd: i32) -> i32;
extern fn exit(code: i32) -> i32;
extern fn load8(ptr: i32) -> i32;
extern fn store8(ptr: i32, val: i32) -> i32;
extern "C" fn hf_asm_pool_create(block_size: i32, block_count: i32) -> i32;
extern "C" fn hf_asm_pool_alloc(pool: i32) -> i32;
extern "C" fn hf_asm_pool_destroy(pool: i32) -> i32;

static path: [i8] = "input.em";
static zero: [i8] = "0";
static pbuf: [i8] = "            ";
static state: [i8] = "        ";
static stbak: [i8] = "        ";
static lblc: [i8] = "  ";
static modes: [i8] = "  ";
static f_manual: [i8] = "-manual";
static f_gc: [i8] = "-gc";
static n_alloc: [i8] = "alloc";
static s_err: [i8] = "parse error\n";

static kw_fn: [i8] = "fn";
static kw_let: [i8] = "let";
static kw_if: [i8] = "if";
static kw_else: [i8] = "else";
static kw_while: [i8] = "while";
static kw_return: [i8] = "return";
static kw_extern: [i8] = "extern";
static kw_static: [i8] = "static";

static n_exit: [i8] = "exit";
static n_read: [i8] = "read";
static n_write: [i8] = "write";
static n_open: [i8] = "open";
static n_close: [i8] = "close";
static n_load8: [i8] = "load8";
static n_store8: [i8] = "store8";
static n_mmap: [i8] = "mmap";
static n_munmap: [i8] = "munmap";
static n_load64: [i8] = "load64";
static n_store64: [i8] = "store64";
static n_load32: [i8] = "load32";
static n_i64: [i8] = "i64";

static g_head: [i8] = "// Generated by emberc (Ember self-hosted, stage 4)\n.text\n";
static g_fn1: [i8] = ".p2align 2\n.globl _";
static g_us: [i8] = "\n_";
static g_fn2: [i8] = ":\n\tstp x29, x30, [sp, #-16]!\n\tmov x29, sp\n\tsub sp, sp, #128\n";
static g_par1: [i8] = "\tstr x";
static g_par2: [i8] = ", [x29, #-";
static g_close: [i8] = "]\n";
static g_epi: [i8] = "\tmov sp, x29\n\tldp x29, x30, [sp], #16\n\tret\n";
static g_zero: [i8] = "\tmov x0, #0\n";
static g_movx0: [i8] = "\tmov x0, #";
static g_nl: [i8] = "\n";
static g_push: [i8] = "\tstr x0, [sp, #-16]!\n";
static g_pop9: [i8] = "\tldr x9, [sp], #16\n";
static g_ldr1: [i8] = "\tldr x0, [x29, #-";
static g_str1: [i8] = "\tstr x0, [x29, #-";
static g_ldr1x: [i8] = "\tldr x0, [x29, #-";
static g_str1x: [i8] = "\tstr x0, [x29, #-";
static g_add: [i8] = "\tadd x0, x9, x0\n";
static g_sub: [i8] = "\tsub x0, x9, x0\n";
static g_mul: [i8] = "\tmul x0, x9, x0\n";
static g_div: [i8] = "\tsdiv x0, x9, x0\n";
static g_mod: [i8] = "\tsdiv x10, x9, x0\n\tmsub x0, x10, x0, x9\n";
static g_cmp: [i8] = "\tcmp x9, x0\n\tcset x0, ";
static c_eq: [i8] = "eq\n";
static c_ne: [i8] = "ne\n";
static c_lt: [i8] = "lt\n";
static c_gt: [i8] = "gt\n";
static c_le: [i8] = "le\n";
static c_ge: [i8] = "ge\n";
static g_cbz: [i8] = "\tcbz x0, L";
static g_b: [i8] = "\tb L";
static g_L: [i8] = "L";
static g_colon: [i8] = ":\n";
static g_bl: [i8] = "\tbl _";
static g_popr: [i8] = "\tldr x";
static g_popr2: [i8] = ", [sp], #16\n";
static g_svc1: [i8] = "\tmov x16, #";
static g_svc2: [i8] = "\tmovk x16, #0x0200, lsl #16\n\tsvc #0x80\n";
static g_ldrb: [i8] = "\tldrb w0, [x0]\n";
static g_strb: [i8] = "\tstrb w1, [x0]\n\tmov x0, #0\n";
static g_ldr64: [i8] = "\tldr x0, [x0]\n";
static g_str64: [i8] = "\tstr x1, [x0]\n\tmov x0, #0\n";
static g_ldr32: [i8] = "\tldr w0, [x0]\n";
static g_and: [i8] = "\tand x0, x9, x0\n";
static g_orr: [i8] = "\torr x0, x9, x0\n";
static g_eor: [i8] = "\teor x0, x9, x0\n";
static g_lsl: [i8] = "\tlsl x0, x9, x0\n";
static g_lsr: [i8] = "\tlsr x0, x9, x0\n";
static g_mvn: [i8] = "\tmvn x0, x0\n";
static g_d1: [i8] = ".section __DATA,__data\n_static_";
static g_d2: [i8] = ": .asciz \"";
static g_d3: [i8] = "\"\n.text\n";
static g_adrp1: [i8] = "\tadrp x0, _static_";
static g_adrp2: [i8] = "@PAGE\n\tadd x0, x0, _static_";
static g_adrp3: [i8] = "@PAGEOFF\n";
static g_rtfree: [i8] = "\tbl _rt_free\n";
static g_gcpush: [i8] = "\tmov x0, x29\n\tbl _gc_push_frame\n";
static g_gcpop: [i8] = "\tbl _gc_pop_frame\n";
static g_pop0: [i8] = "\tldr x0, [sp], #16\n";
static g_z1: [i8] = "\tstp xzr, xzr, [x29, #-";

fn is_alpha(c: i32) -> i32 {
    return 0 < (65 <= c) * (c <= 90) + (97 <= c) * (c <= 122) + (c == 95);
}

fn is_digit(c: i32) -> i32 {
    return (48 <= c) * (c <= 57);
}

fn is_ws(c: i32) -> i32 {
    return 0 < (c == 32) + (c == 10) + (c == 13) + (c == 9);
}

fn mem_eq(a: i32, b: i32, n: i32) -> i32 {
    let j: i32 = 0;
    while j < n {
        if load8(a + j) != load8(b + j) { return 0; }
        j = j + 1;
    }
    return 1;
}

fn kw_match(start: i32, len: i32, kw: i32) -> i32 {
    if mem_eq(start, kw, len) == 0 { return 0; }
    if load8(kw + len) == 0 { return 1; }
    return 0;
}

fn classify_ident(start: i32, len: i32) -> i32 {
    if kw_match(start, len, kw_fn) == 1 { return 10; }
    if kw_match(start, len, kw_let) == 1 { return 11; }
    if kw_match(start, len, kw_if) == 1 { return 12; }
    if kw_match(start, len, kw_else) == 1 { return 13; }
    if kw_match(start, len, kw_while) == 1 { return 14; }
    if kw_match(start, len, kw_return) == 1 { return 15; }
    if kw_match(start, len, kw_extern) == 1 { return 16; }
    if kw_match(start, len, kw_static) == 1 { return 17; }
    return 1;
}

fn get16(a: i32) -> i32 {
    return load8(a) + load8(a + 1) * 256;
}

fn put16(a: i32, v: i32) -> i32 {
    store8(a, v % 256);
    store8(a + 1, v / 256);
    return 0;
}

fn get64(a: i32) -> i32 {
    let v: i32 = 0;
    let j: i32 = 8;
    while j > 0 {
        j = j - 1;
        v = v * 256 + load8(a + j);
    }
    return v;
}

// token 回放：state 7 字节备份/恢复，实现单 token lookahead（intern 幂等，重放无害）
fn save_state() -> i32 {
    let j: i32 = 0;
    while j < 7 {
        store8(stbak + j, load8(state + j));
        j = j + 1;
    }
    return 0;
}

fn restore_state() -> i32 {
    let j: i32 = 0;
    while j < 7 {
        store8(state + j, load8(stbak + j));
        j = j + 1;
    }
    return 0;
}

fn intern(tab: i32, buf: i32, st: i32, len: i32) -> i32 {
    let count: i32 = get16(tab);
    let k: i32 = 0;
    while k < count {
        let e: i32 = tab + 4 + k * 4;
        if load8(e) == len {
            if mem_eq(buf + get16(e + 1), buf + st, len) == 1 {
                return k + 1;
            }
        }
        k = k + 1;
    }
    let e2: i32 = tab + 4 + count * 4;
    store8(e2, len);
    put16(e2 + 1, st);
    let nc: i32 = count + 1;
    put16(tab, nc);
    return nc;
}

fn slen(s: i32) -> i32 {
    let i: i32 = 0;
    while load8(s + i) != 0 { i = i + 1; }
    return i;
}

fn outs(s: i32) -> i32 {
    write(1, s, slen(s));
    return 0;
}

fn print_int(num: i32) -> i32 {
    if num == 0 {
        write(1, zero, 1);
        return 0;
    }
    let n: i32 = num;
    let idx: i32 = 12;
    while n > 0 {
        idx = idx - 1;
        let d: i32 = n % 10;
        store8(pbuf + idx, d + 48);
        n = n / 10;
    }
    write(1, pbuf + idx, 12 - idx);
    return 0;
}

fn out_name(tab: i32, buf: i32, sym: i32) -> i32 {
    let e: i32 = tab + 4 + (sym - 1) * 4;
    write(1, buf + get16(e + 1), load8(e));
    return 0;
}

fn cur_type() -> i32 {
    return load8(state + 2);
}

fn cur_val() -> i32 {
    return get16(state + 3);
}

fn cur_aux() -> i32 {
    return get16(state + 5);
}

fn parse_error() -> i32 {
    write(1, s_err, 12);
    exit(1);
    return 0;
}

fn advance(buf: i32, len: i32, tab: i32) -> i32 {
    let pos: i32 = get16(state);
    let g: i32 = 0;
    let d: i32 = 0;
    let sk: i32 = 1;
    while sk == 1 {
        sk = 0;
        if pos < len {
            if is_ws(load8(buf + pos)) == 1 {
                pos = pos + 1;
                sk = 1;
            }
        }
        if sk == 0 {
            if pos + 1 < len {
                if (load8(buf + pos) == 47) * (load8(buf + pos + 1) == 47) == 1 {
                    g = 1;
                    while (g == 1) * (pos < len) == 1 {
                        if load8(buf + pos) == 10 { g = 0; }
                        pos = pos + 1;
                    }
                    sk = 1;
                }
            }
        }
    }
    let ty: i32 = 0;
    let val: i32 = 0;
    let aux: i32 = 0;
    if pos < len {
        let c: i32 = load8(buf + pos);
        if is_digit(c) == 1 {
            ty = 2;
            g = 1;
            while (g == 1) * (pos < len) == 1 {
                d = load8(buf + pos);
                if is_digit(d) == 1 {
                    val = val * 10 + d - 48;
                    pos = pos + 1;
                } else { g = 0; }
            }
        } else { if is_alpha(c) == 1 {
            let st2: i32 = pos;
            g = 1;
            while (g == 1) * (pos < len) == 1 {
                d = load8(buf + pos);
                if 0 < is_alpha(d) + is_digit(d) { pos = pos + 1; } else { g = 0; }
            }
            ty = classify_ident(buf + st2, pos - st2);
            val = intern(tab, buf, st2, pos - st2);
        } else { if c == 34 {
            ty = 34;
            pos = pos + 1;
            aux = pos;
            g = 1;
            while (g == 1) * (pos < len) == 1 {
                d = load8(buf + pos);
                if d == 34 { g = 0; } else {
                    if d == 92 { pos = pos + 2; } else { pos = pos + 1; }
                }
            }
            val = pos - aux;
            pos = pos + 1;
        } else {
            ty = c;
            pos = pos + 1;
            if 0 < (c == 61) + (c == 33) + (c == 60) + (c == 62) {
                if pos < len {
                    if load8(buf + pos) == 61 {
                        if c == 61 { ty = 200; }
                        if c == 33 { ty = 201; }
                        if c == 60 { ty = 202; }
                        if c == 62 { ty = 203; }
                        pos = pos + 1;
                    }
                }
            }
            if ty == 60 {
                if pos < len {
                    if load8(buf + pos) == 60 { ty = 204; pos = pos + 1; }
                }
            }
            if ty == 62 {
                if pos < len {
                    if load8(buf + pos) == 62 { ty = 205; pos = pos + 1; }
                }
            }
        } } }
    }
    put16(state, pos);
    store8(state + 2, ty);
    put16(state + 3, val);
    put16(state + 5, aux);
    return 0;
}

fn eat(buf: i32, len: i32, tab: i32, t: i32) -> i32 {
    if cur_type() != t { parse_error(); }
    advance(buf, len, tab);
    return 0;
}

fn next_label() -> i32 {
    let v: i32 = get16(lblc);
    put16(lblc, v + 1);
    return v;
}

// ---- 三表（vtab / etab / stab 共居 tbl 块）----
// vtab 条目 4B = [sym16][flags16]，flags bit0 = owning（-manual 块尾自动 free）
//                                  flags bit1 = i64（原生 64 位槽位，走 x 寄存器全宽存取）

fn add_var(tbl: i32, sym: i32) -> i32 {
    let c: i32 = get16(tbl);
    if c == 16 { parse_error(); }
    put16(tbl + 2 + c * 4, sym);
    put16(tbl + 4 + c * 4, 0);
    put16(tbl, c + 1);
    return c + 1;
}

fn set_owning(tbl: i32, v: i32) -> i32 {
    put16(tbl + 4 + (v - 1) * 4, var_flag(tbl, v) + 1);
    return 0;
}

fn set_i64(tbl: i32, v: i32) -> i32 {
    put16(tbl + 4 + (v - 1) * 4, var_flag(tbl, v) + 2);
    return 0;
}

fn var_flag(tbl: i32, v: i32) -> i32 {
    return get16(tbl + 4 + (v - 1) * 4);
}

fn lookup_var(tbl: i32, sym: i32) -> i32 {
    let k: i32 = get16(tbl);
    while k > 0 {
        k = k - 1;
        if get16(tbl + 2 + k * 4) == sym { return k + 1; }
    }
    return 0;
}

fn add_ext(tbl: i32, sym: i32, kind: i32) -> i32 {
    let e: i32 = tbl + 256;
    let c: i32 = get16(e);
    put16(e + 2 + c * 4, sym);
    put16(e + 4 + c * 4, kind);
    put16(e, c + 1);
    return 0;
}

fn lookup_ext(tbl: i32, sym: i32) -> i32 {
    let e: i32 = tbl + 256;
    let c: i32 = get16(e);
    let k: i32 = 0;
    while k < c {
        if get16(e + 2 + k * 4) == sym { return get16(e + 4 + k * 4) + 1; }
        k = k + 1;
    }
    return 0;
}

fn add_static(tbl: i32, sym: i32) -> i32 {
    let e: i32 = tbl + 1024;
    let c: i32 = get16(e);
    put16(e + 2 + c * 2, sym);
    put16(e, c + 1);
    return c + 1;
}

fn lookup_static(tbl: i32, sym: i32) -> i32 {
    let e: i32 = tbl + 1024;
    let c: i32 = get16(e);
    let k: i32 = 0;
    while k < c {
        if get16(e + 2 + k * 2) == sym { return k + 1; }
        k = k + 1;
    }
    return 0;
}

fn sym_is(tab: i32, buf: i32, sym: i32, s: i32) -> i32 {
    let e: i32 = tab + 4 + (sym - 1) * 4;
    return kw_match(buf + get16(e + 1), load8(e), s);
}

fn sys_kind(tab: i32, buf: i32, sym: i32) -> i32 {
    if sym_is(tab, buf, sym, n_exit) == 1 { return 1; }
    if sym_is(tab, buf, sym, n_read) == 1 { return 3; }
    if sym_is(tab, buf, sym, n_write) == 1 { return 4; }
    if sym_is(tab, buf, sym, n_open) == 1 { return 5; }
    if sym_is(tab, buf, sym, n_close) == 1 { return 6; }
    if sym_is(tab, buf, sym, n_load8) == 1 { return 4097; }
    if sym_is(tab, buf, sym, n_store8) == 1 { return 4098; }
    if sym_is(tab, buf, sym, n_mmap) == 1 { return 197; }
    if sym_is(tab, buf, sym, n_munmap) == 1 { return 73; }
    if sym_is(tab, buf, sym, n_load64) == 1 { return 4099; }
    if sym_is(tab, buf, sym, n_store64) == 1 { return 4100; }
    if sym_is(tab, buf, sym, n_load32) == 1 { return 4101; }
    return 65535;
}

// ---- 表达式代码生成（后缀流式，结果恒在 x0）----

fn gen_call(buf: i32, len: i32, tab: i32, tbl: i32, id: i32) -> i32 {
    advance(buf, len, tab);
    let argc: i32 = 0;
    if cur_type() != 41 {
        let go: i32 = 1;
        while go == 1 {
            gen_expr(buf, len, tab, tbl);
            outs(g_push);
            argc = argc + 1;
            if cur_type() == 44 { advance(buf, len, tab); } else { go = 0; }
        }
    }
    eat(buf, len, tab, 41);
    let k: i32 = argc;
    while k > 0 {
        k = k - 1;
        outs(g_popr);
        print_int(k);
        outs(g_popr2);
    }
    let kd: i32 = lookup_ext(tbl, id);
    if kd == 0 {
        outs(g_bl);
        out_name(tab, buf, id);
        outs(g_nl);
        return 0;
    }
    let kind: i32 = kd - 1;
    if kind == 0 {
        outs(g_bl);
        out_name(tab, buf, id);
        outs(g_nl);
        return 0;
    }
    if kind == 4097 { outs(g_ldrb); return 0; }
    if kind == 4098 { outs(g_strb); return 0; }
    if kind == 4099 { outs(g_ldr64); return 0; }
    if kind == 4100 { outs(g_str64); return 0; }
    if kind == 4101 { outs(g_ldr32); return 0; }
    outs(g_svc1);
    print_int(kind);
    outs(g_nl);
    outs(g_svc2);
    return 0;
}

fn gen_factor(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    let ty: i32 = cur_type();
    if ty == 126 {
        advance(buf, len, tab);
        gen_factor(buf, len, tab, tbl);
        outs(g_mvn);
        return 0;
    }
    if ty == 2 {
        outs(g_movx0);
        print_int(cur_val());
        outs(g_nl);
        advance(buf, len, tab);
        return 0;
    }
    if ty == 1 {
        let id: i32 = cur_val();
        advance(buf, len, tab);
        if cur_type() == 40 {
            gen_call(buf, len, tab, tbl, id);
            return 0;
        }
        let v: i32 = lookup_var(tbl, id);
        if v > 0 {
            if var_flag(tbl, v) >= 2 { outs(g_ldr1x); } else { outs(g_ldr1); }
            print_int(v * 8);
            outs(g_close);
            return 0;
        }
        let s: i32 = lookup_static(tbl, id);
        if s > 0 {
            outs(g_adrp1);
            print_int(s - 1);
            outs(g_adrp2);
            print_int(s - 1);
            outs(g_adrp3);
            return 0;
        }
        parse_error();
    }
    if ty == 40 {
        advance(buf, len, tab);
        gen_expr(buf, len, tab, tbl);
        eat(buf, len, tab, 41);
        return 0;
    }
    parse_error();
    return 0;
}

fn gen_term(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    gen_factor(buf, len, tab, tbl);
    let go: i32 = 1;
    while go == 1 {
        let ty: i32 = cur_type();
        if 0 < (ty == 42) + (ty == 47) + (ty == 37) {
            outs(g_push);
            advance(buf, len, tab);
            gen_factor(buf, len, tab, tbl);
            outs(g_pop9);
            if ty == 42 { outs(g_mul); }
            if ty == 47 { outs(g_div); }
            if ty == 37 { outs(g_mod); }
        } else { go = 0; }
    }
    return 0;
}

fn gen_add(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    gen_term(buf, len, tab, tbl);
    let go: i32 = 1;
    while go == 1 {
        let ty: i32 = cur_type();
        if 0 < (ty == 43) + (ty == 45) {
            outs(g_push);
            advance(buf, len, tab);
            gen_term(buf, len, tab, tbl);
            outs(g_pop9);
            if ty == 43 { outs(g_add); }
            if ty == 45 { outs(g_sub); }
        } else { go = 0; }
    }
    return 0;
}

// 优先级链（C 序）：factor(~) -> term(* / %) -> add(+ -) -> shift(<< >>)
//   -> cmp(比较，非结合) -> band(&) -> bxor(^) -> bor(|) = gen_expr
fn gen_shift(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    gen_add(buf, len, tab, tbl);
    let go: i32 = 1;
    while go == 1 {
        let ty: i32 = cur_type();
        if 0 < (ty == 204) + (ty == 205) {
            outs(g_push);
            advance(buf, len, tab);
            gen_add(buf, len, tab, tbl);
            outs(g_pop9);
            if ty == 204 { outs(g_lsl); }
            if ty == 205 { outs(g_lsr); }
        } else { go = 0; }
    }
    return 0;
}

fn gen_cmp(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    gen_shift(buf, len, tab, tbl);
    let ty: i32 = cur_type();
    if 0 < (ty == 60) + (ty == 62) + (ty == 200) + (ty == 201) + (ty == 202) + (ty == 203) {
        outs(g_push);
        advance(buf, len, tab);
        gen_shift(buf, len, tab, tbl);
        outs(g_pop9);
        outs(g_cmp);
        if ty == 200 { outs(c_eq); }
        if ty == 201 { outs(c_ne); }
        if ty == 60 { outs(c_lt); }
        if ty == 62 { outs(c_gt); }
        if ty == 202 { outs(c_le); }
        if ty == 203 { outs(c_ge); }
    }
    return 0;
}

fn gen_band(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    gen_cmp(buf, len, tab, tbl);
    let go: i32 = 1;
    while go == 1 {
        if cur_type() == 38 {
            outs(g_push);
            advance(buf, len, tab);
            gen_cmp(buf, len, tab, tbl);
            outs(g_pop9);
            outs(g_and);
        } else { go = 0; }
    }
    return 0;
}

fn gen_bxor(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    gen_band(buf, len, tab, tbl);
    let go: i32 = 1;
    while go == 1 {
        if cur_type() == 94 {
            outs(g_push);
            advance(buf, len, tab);
            gen_band(buf, len, tab, tbl);
            outs(g_pop9);
            outs(g_eor);
        } else { go = 0; }
    }
    return 0;
}

fn gen_expr(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    gen_bxor(buf, len, tab, tbl);
    let go: i32 = 1;
    while go == 1 {
        if cur_type() == 124 {
            outs(g_push);
            advance(buf, len, tab);
            gen_bxor(buf, len, tab, tbl);
            outs(g_pop9);
            outs(g_orr);
        } else { go = 0; }
    }
    return 0;
}

// ---- 语句代码生成 ----

// 统一尾声：-manual 先 free 本函数 owning 槽（skip 豁免逃逸槽），
// -gc 注销根帧；x0 经 sp 栈保护穿越运行时调用
fn gen_epi_seq(tbl: i32, skip: i32) -> i32 {
    let m: i32 = get16(modes);
    if m == 1 {
        let c: i32 = get16(tbl);
        let any: i32 = 0;
        let k: i32 = 0;
        while k < c {
            if var_flag(tbl, k + 1) % 2 == 1 {
                if k + 1 != skip { any = any + 1; }
            }
            k = k + 1;
        }
        if any > 0 {
            outs(g_push);
            k = 0;
            while k < c {
                if var_flag(tbl, k + 1) % 2 == 1 {
                    if k + 1 != skip {
                        outs(g_ldr1);
                        print_int((k + 1) * 8);
                        outs(g_close);
                        outs(g_rtfree);
                    }
                }
                k = k + 1;
            }
            outs(g_pop0);
        }
    }
    if m == 2 {
        outs(g_push);
        outs(g_gcpop);
        outs(g_pop0);
    }
    outs(g_epi);
    return 0;
}

// return 语句（'return' 已消费）：纯变量 return 用 lookahead 豁免该槽的 free
fn gen_return(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    let rid: i32 = 0;
    if cur_type() == 59 {
        outs(g_zero);
    } else {
        if cur_type() == 1 {
            save_state();
            let idt: i32 = cur_val();
            advance(buf, len, tab);
            if cur_type() == 59 {
                let vv: i32 = lookup_var(tbl, idt);
                if vv > 0 { rid = vv; }
            }
            restore_state();
        }
        gen_expr(buf, len, tab, tbl);
    }
    gen_epi_seq(tbl, rid);
    eat(buf, len, tab, 59);
    return 0;
}

fn gen_block(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    eat(buf, len, tab, 123);
    let last: i32 = 0;
    while (cur_type() != 125) * (cur_type() != 0) == 1 {
        last = gen_stmt(buf, len, tab, tbl);
    }
    eat(buf, len, tab, 125);
    return last;
}

fn gen_stmt(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    let ty: i32 = cur_type();
    if ty == 11 {
        advance(buf, len, tab);
        let name: i32 = cur_val();
        eat(buf, len, tab, 1);
        eat(buf, len, tab, 58);
        let t64: i32 = 0;
        if sym_is(tab, buf, cur_val(), n_i64) == 1 { t64 = 1; }
        eat(buf, len, tab, 1);
        eat(buf, len, tab, 61);
        let own: i32 = 0;
        if get16(modes) == 1 {
            if cur_type() == 1 {
                if sym_is(tab, buf, cur_val(), n_alloc) == 1 { own = 1; }
            }
        }
        gen_expr(buf, len, tab, tbl);
        let v: i32 = add_var(tbl, name);
        if own == 1 { set_owning(tbl, v); }
        if t64 == 1 { set_i64(tbl, v); }
        if t64 == 1 { outs(g_str1x); } else { outs(g_str1); }
        print_int(v * 8);
        outs(g_close);
        eat(buf, len, tab, 59);
        return 0;
    }
    if ty == 12 {
        advance(buf, len, tab);
        gen_expr(buf, len, tab, tbl);
        let l: i32 = next_label();
        outs(g_cbz);
        print_int(l);
        outs(g_nl);
        gen_block(buf, len, tab, tbl);
        if cur_type() == 13 {
            advance(buf, len, tab);
            let l2: i32 = next_label();
            outs(g_b);
            print_int(l2);
            outs(g_nl);
            outs(g_L);
            print_int(l);
            outs(g_colon);
            gen_block(buf, len, tab, tbl);
            outs(g_L);
            print_int(l2);
            outs(g_colon);
        } else {
            outs(g_L);
            print_int(l);
            outs(g_colon);
        }
        return 0;
    }
    if ty == 14 {
        advance(buf, len, tab);
        let lw: i32 = next_label();
        let le: i32 = next_label();
        outs(g_L);
        print_int(lw);
        outs(g_colon);
        gen_expr(buf, len, tab, tbl);
        outs(g_cbz);
        print_int(le);
        outs(g_nl);
        gen_block(buf, len, tab, tbl);
        outs(g_b);
        print_int(lw);
        outs(g_nl);
        outs(g_L);
        print_int(le);
        outs(g_colon);
        return 0;
    }
    if ty == 15 {
        advance(buf, len, tab);
        gen_return(buf, len, tab, tbl);
        return 15;
    }
    if ty == 1 {
        let id: i32 = cur_val();
        advance(buf, len, tab);
        if cur_type() == 61 {
            advance(buf, len, tab);
            gen_expr(buf, len, tab, tbl);
            let v2: i32 = lookup_var(tbl, id);
            if v2 == 0 { parse_error(); }
            if var_flag(tbl, v2) >= 2 { outs(g_str1x); } else { outs(g_str1); }
            print_int(v2 * 8);
            outs(g_close);
            eat(buf, len, tab, 59);
            return 0;
        }
        if cur_type() == 40 {
            gen_call(buf, len, tab, tbl, id);
            eat(buf, len, tab, 59);
            return 0;
        }
        parse_error();
    }
    if ty == 123 {
        gen_block(buf, len, tab, tbl);
        return 0;
    }
    parse_error();
    return 0;
}

// ---- 顶层声明 ----

fn gen_params(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    let argc: i32 = 0;
    if cur_type() == 1 {
        let go: i32 = 1;
        while go == 1 {
            let pv: i32 = add_var(tbl, cur_val());
            eat(buf, len, tab, 1);
            eat(buf, len, tab, 58);
            if sym_is(tab, buf, cur_val(), n_i64) == 1 { set_i64(tbl, pv); }
            eat(buf, len, tab, 1);
            argc = argc + 1;
            if cur_type() == 44 { advance(buf, len, tab); } else { go = 0; }
        }
    }
    return argc;
}

fn gen_fn(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    eat(buf, len, tab, 10);
    let name: i32 = cur_val();
    eat(buf, len, tab, 1);
    put16(tbl, 0);
    eat(buf, len, tab, 40);
    let argc: i32 = gen_params(buf, len, tab, tbl);
    eat(buf, len, tab, 41);
    if cur_type() == 45 {
        advance(buf, len, tab);
        eat(buf, len, tab, 62);
        eat(buf, len, tab, 1);
    }
    outs(g_fn1);
    out_name(tab, buf, name);
    outs(g_us);
    out_name(tab, buf, name);
    outs(g_fn2);
    if get16(modes) == 2 {
        let z: i32 = 16;                // -gc：帧清零（杆掉保守扫描的栈残渣假阳性）
        while z <= 128 {
            outs(g_z1);
            print_int(z);
            outs(g_close);
            z = z + 16;
        }
    }
    let i: i32 = 0;
    while i < argc {
        outs(g_par1);
        print_int(i);
        outs(g_par2);
        print_int(8 + i * 8);
        outs(g_close);
        i = i + 1;
    }
    if get16(modes) == 2 { outs(g_gcpush); }    // 参数入槽后注册根帧（bl 毁 x0-x7）
    let last: i32 = gen_block(buf, len, tab, tbl);
    if last != 15 {                             // 末语句非 return 才需兜底尾声（死代码消除）
        outs(g_zero);
        gen_epi_seq(tbl, 0);
    }
    return 0;
}

fn gen_extern(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    eat(buf, len, tab, 16);
    let isc: i32 = 0;
    if cur_type() == 34 {
        isc = 1;
        advance(buf, len, tab);
    }
    eat(buf, len, tab, 10);
    let name: i32 = cur_val();
    eat(buf, len, tab, 1);
    put16(tbl, 0);
    eat(buf, len, tab, 40);
    gen_params(buf, len, tab, tbl);
    eat(buf, len, tab, 41);
    if cur_type() == 45 {
        advance(buf, len, tab);
        eat(buf, len, tab, 62);
        eat(buf, len, tab, 1);
    }
    let kind: i32 = 0;
    if isc == 0 {
        kind = sys_kind(tab, buf, name);
        if kind == 65535 { parse_error(); }
    }
    add_ext(tbl, name, kind);
    eat(buf, len, tab, 59);
    return 0;
}

fn gen_static(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    eat(buf, len, tab, 17);
    let name: i32 = cur_val();
    eat(buf, len, tab, 1);
    eat(buf, len, tab, 58);
    eat(buf, len, tab, 91);
    eat(buf, len, tab, 1);
    eat(buf, len, tab, 93);
    eat(buf, len, tab, 61);
    if cur_type() != 34 { parse_error(); }
    let sn: i32 = add_static(tbl, name);
    outs(g_d1);
    print_int(sn - 1);
    outs(g_d2);
    write(1, buf + cur_aux(), cur_val());
    outs(g_d3);
    advance(buf, len, tab);
    eat(buf, len, tab, 59);
    return 0;
}

fn main(argc: i32, argv: i32) -> i32 {
    put16(modes, 0);
    if argc > 1 {
        let a1: i32 = get64(argv + 8);
        if kw_match(a1, slen(a1), f_manual) == 1 { put16(modes, 1); }
        if kw_match(a1, slen(a1), f_gc) == 1 { put16(modes, 2); }
    }
    let pool: i32 = hf_asm_pool_create(32768, 3);
    if pool == 0 { return 255; }
    let buf: i32 = hf_asm_pool_alloc(pool);
    let tab: i32 = hf_asm_pool_alloc(pool);
    let tbl: i32 = hf_asm_pool_alloc(pool);
    if tbl == 0 { return 254; }
    put16(tab, 0);
    put16(tbl, 0);
    put16(tbl + 256, 0);
    put16(tbl + 1024, 0);
    put16(lblc, 0);
    let fd: i32 = open(path, 0);
    if fd < 3 { return 253; }
    let len: i32 = read(fd, buf, 32767);
    close(fd);

    outs(g_head);
    put16(state, 0);
    advance(buf, len, tab);
    let go: i32 = 1;
    while go == 1 {
        let t: i32 = cur_type();
        if t == 0 { go = 0; } else {
            if t == 16 { gen_extern(buf, len, tab, tbl); } else {
                if t == 17 { gen_static(buf, len, tab, tbl); } else {
                    if t == 10 { gen_fn(buf, len, tab, tbl); } else {
                        parse_error();
                    }
                }
            }
        }
    }

    hf_asm_pool_destroy(pool);
    return 0;
}
