// lexer8.em - 自托管 Ember 编译器（阶段 2 后半：字符串标准库）
// 新增：字符串标准库四件套 str_len / str_append / str_eq / str_to_int
//   extern kind 8193-8196；stdused 位掩码（1/2/4/8），main 尾部按需发射函数体
//   字符串 = NUL 结尾指针；str_append 结果从生成程序自带 bump 堆分配
// 新增：字符串字面量入表达式 -> 匿名 _lit<N> .asciz + adrp（litc 计数）
// 继承：阶段 1（for/break/continue/行号报错/64位字面量）
//       阶段 2 前半（struct/数组/new/后缀链）

extern fn open(path: i32, flags: i32) -> i32;
extern fn read(fd: i32, buf: i32, len: i32) -> i32;
extern fn write(fd: i32, buf: i32, len: i32) -> i32;
extern fn close(fd: i32) -> i32;
extern fn exit(code: i32) -> i32;
extern fn load8(ptr: i32) -> i32;
extern fn store8(ptr: i32, val: i32) -> i32;
extern "C" fn hf_asm_pool_create(block_size: i32, block_count: i32) -> i32;
extern "C" fn hf_asm_pool_alloc(pool: i32) -> i32;
extern "C" fn hf_asm_pool_destroy(pool: i32) -> i32;

static path: [i8] = "input.em";
static zero: [i8] = "0";
static pbuf: [i8] = "            ";
static state: [i8] = "                ";
static stbak: [i8] = "                ";
static tokpos: [i8] = "  ";
static lblc: [i8] = "  ";
static modes: [i8] = "  ";
static curline: [i8] = "  ";
static loopstk: [i8] = "00000000000000000000000000000000000000000000000000";
static f_manual: [i8] = "-manual";
static f_gc: [i8] = "-gc";
static n_alloc: [i8] = "alloc";
static s_errl: [i8] = "parse error on line ";
static s_tok: [i8] = " (token ";
static s_tok2: [i8] = ")\n";
static stmp: [i8] = "0000000000000000000000000000000000000000000000000000000000000000";
static stdused: [i8] = "  ";
static litc: [i8] = "  ";

static kw_fn: [i8] = "fn";
static kw_let: [i8] = "let";
static kw_if: [i8] = "if";
static kw_else: [i8] = "else";
static kw_while: [i8] = "while";
static kw_return: [i8] = "return";
static kw_extern: [i8] = "extern";
static kw_static: [i8] = "static";
static kw_for: [i8] = "for";
static kw_break: [i8] = "break";
static kw_continue: [i8] = "continue";
static kw_struct: [i8] = "struct";
static kw_new: [i8] = "new";

static n_exit: [i8] = "exit";
static n_read: [i8] = "read";
static n_write: [i8] = "write";
static n_open: [i8] = "open";
static n_close: [i8] = "close";
static n_load8: [i8] = "load8";
static n_store8: [i8] = "store8";
static n_mmap: [i8] = "mmap";
static n_munmap: [i8] = "munmap";
static n_load64: [i8] = "load64";
static n_store64: [i8] = "store64";
static n_load32: [i8] = "load32";
static n_i32: [i8] = "i32";
static n_i64: [i8] = "i64";
static n_strlen: [i8] = "str_len";
static n_strappend: [i8] = "str_append";
static n_streq: [i8] = "str_eq";
static n_strtoi: [i8] = "str_to_int";

static g_head: [i8] = "// Generated by emberc (Ember self-hosted, stage 4)\n.text\n";
static g_fn1: [i8] = ".p2align 2\n.globl _";
static g_us: [i8] = "\n_";
static g_fn2: [i8] = ":\n\tstp x29, x30, [sp, #-16]!\n\tmov x29, sp\n\tsub sp, sp, #128\n";
static g_par1: [i8] = "\tstr x";
static g_par2: [i8] = ", [x29, #-";
static g_close: [i8] = "]\n";
static g_epi: [i8] = "\tmov sp, x29\n\tldp x29, x30, [sp], #16\n\tret\n";
static g_zero: [i8] = "\tmov x0, #0\n";
static g_movx0: [i8] = "\tmov x0, #";
static g_movz: [i8] = "\tmovz x0, #";
static g_movk: [i8] = "\tmovk x0, #";
static g_lslt: [i8] = ", lsl #";
static g_nl: [i8] = "\n";
static g_push: [i8] = "\tstr x0, [sp, #-16]!\n";
static g_pop9: [i8] = "\tldr x9, [sp], #16\n";
static g_ldr1: [i8] = "\tldr x0, [x29, #-";
static g_str1: [i8] = "\tstr x0, [x29, #-";
static g_ldr1x: [i8] = "\tldr x0, [x29, #-";
static g_str1x: [i8] = "\tstr x0, [x29, #-";
static g_add: [i8] = "\tadd x0, x9, x0\n";
static g_sub: [i8] = "\tsub x0, x9, x0\n";
static g_mul: [i8] = "\tmul x0, x9, x0\n";
static g_div: [i8] = "\tsdiv x0, x9, x0\n";
static g_mod: [i8] = "\tsdiv x10, x9, x0\n\tmsub x0, x10, x0, x9\n";
static g_cmp: [i8] = "\tcmp x9, x0\n\tcset x0, ";
static c_eq: [i8] = "eq\n";
static c_ne: [i8] = "ne\n";
static c_lt: [i8] = "lt\n";
static c_gt: [i8] = "gt\n";
static c_le: [i8] = "le\n";
static c_ge: [i8] = "ge\n";
static g_cbz: [i8] = "\tcbz x0, L";
static g_b: [i8] = "\tb L";
static g_L: [i8] = "L";
static g_colon: [i8] = ":\n";
static g_bl: [i8] = "\tbl _";
static g_popr: [i8] = "\tldr x";
static g_popr2: [i8] = ", [sp], #16\n";
static g_svc1: [i8] = "\tmov x16, #";
static g_svc2: [i8] = "\tmovk x16, #0x0200, lsl #16\n\tsvc #0x80\n";
static g_ldrb: [i8] = "\tldrb w0, [x0]\n";
static g_strb: [i8] = "\tstrb w1, [x0]\n\tmov x0, #0\n";
static g_ldr64: [i8] = "\tldr x0, [x0]\n";
static g_str64: [i8] = "\tstr x1, [x0]\n\tmov x0, #0\n";
static g_ldr32: [i8] = "\tldr w0, [x0]\n";
static g_and: [i8] = "\tand x0, x9, x0\n";
static g_orr: [i8] = "\torr x0, x9, x0\n";
static g_eor: [i8] = "\teor x0, x9, x0\n";
static g_lsl: [i8] = "\tlsl x0, x9, x0\n";
static g_lsr: [i8] = "\tlsr x0, x9, x0\n";
static g_mvn: [i8] = "\tmvn x0, x0\n";
static g_d1: [i8] = ".section __DATA,__data\n_static_";
static g_d2: [i8] = ": .asciz \"";
static g_d3: [i8] = "\"\n.text\n";
static g_adrp1: [i8] = "\tadrp x0, _static_";
static g_adrp2: [i8] = "@PAGE\n\tadd x0, x0, _static_";
static g_adrp3: [i8] = "@PAGEOFF\n";
static g_rtfree: [i8] = "\tbl _rt_free\n";
static g_gcpush: [i8] = "\tmov x0, x29\n\tbl _gc_push_frame\n";
static g_gcpop: [i8] = "\tbl _gc_pop_frame\n";
static g_pop0: [i8] = "\tldr x0, [sp], #16\n";
static g_z1: [i8] = "\tstp xzr, xzr, [x29, #-";
static g_heap_data: [i8] = ".section __DATA,__data\n.p2align 3\n_heap_base: .space 65536\n_heap_ctr: .quad _heap_base\n.text\n";
static g_heap_adr: [i8] = "\tadrp x9, _heap_ctr@PAGE\n\tadd x9, x9, _heap_ctr@PAGEOFF\n";
static g_heap_ld: [i8] = "\tldr x0, [x9]\n";
static g_heap_mv: [i8] = "\tmov x10, #";
static g_heap_bmp: [i8] = "\n\tadd x10, x0, x10\n\tstr x10, [x9]\n";
static g_addimm: [i8] = "\tadd x0, x0, #";
static g_lslimm: [i8] = "\tlsl x0, x0, #";
static g_stw9: [i8] = "\tstr w0, [x9]\n";
static g_stx9: [i8] = "\tstr x0, [x9]\n";
static g_lit1: [i8] = ".section __DATA,__data\n_lit";
static g_lit2: [i8] = ": .asciz \"";
static g_litadr1: [i8] = "\tadrp x0, _lit";
static g_litadr2: [i8] = "@PAGE\n\tadd x0, x0, _lit";

// ---- 字符串标准库函数体（main 尾部按 stdused 位掩码发射）----
static s_strlen: [i8] = ".text\n.p2align 2\n_str_len:\n\tmov x1, #0\n_str_len_1:\n\tldrb w2, [x0, x1]\n\tcbz w2, _str_len_2\n\tadd x1, x1, #1\n\tb _str_len_1\n_str_len_2:\n\tmov x0, x1\n\tret\n";
static s_strappend: [i8] = ".p2align 2\n_str_append:\n\tstp x29, x30, [sp, #-16]!\n\tmov x19, x0\n\tmov x20, x1\n\tbl _str_len\n\tmov x21, x0\n\tmov x0, x20\n\tbl _str_len\n\tadd x21, x21, x0\n\tadd x21, x21, #1\n\tadrp x9, _heap_ctr@PAGE\n\tadd x9, x9, _heap_ctr@PAGEOFF\n\tldr x22, [x9]\n\tadd x10, x22, x21\n\tstr x10, [x9]\n\tmov x1, #0\n_str_append_1:\n\tldrb w2, [x19, x1]\n\tstrb w2, [x22, x1]\n\tcbz w2, _str_append_2\n\tadd x1, x1, #1\n\tb _str_append_1\n_str_append_2:\n\tmov x3, #0\n_str_append_3:\n\tldrb w2, [x20, x3]\n\tadd x4, x1, x3\n\tstrb w2, [x22, x4]\n\tcbz w2, _str_append_4\n\tadd x3, x3, #1\n\tb _str_append_3\n_str_append_4:\n\tmov x0, x22\n\tldp x29, x30, [sp], #16\n\tret\n";
static s_streq: [i8] = ".p2align 2\n_str_eq:\n\tmov x2, #0\n_str_eq_1:\n\tldrb w3, [x0, x2]\n\tldrb w4, [x1, x2]\n\tcmp w3, w4\n\tb.ne _str_eq_0\n\tcbz w3, _str_eq_2\n\tadd x2, x2, #1\n\tb _str_eq_1\n_str_eq_2:\n\tmov x0, #1\n\tret\n_str_eq_0:\n\tmov x0, #0\n\tret\n";
static s_strtoi: [i8] = ".p2align 2\n_str_to_int:\n\tmov x1, #0\n\tmov x4, #10\n_str_to_int_1:\n\tldrb w2, [x0], #1\n\tcmp w2, #48\n\tb.lt _str_to_int_2\n\tcmp w2, #57\n\tb.gt _str_to_int_2\n\tsub x2, x2, #48\n\tmul x1, x1, x4\n\tadd x1, x1, x2\n\tb _str_to_int_1\n_str_to_int_2:\n\tmov x0, x1\n\tret\n";

fn is_alpha(c: i32) -> i32 {
    return 0 < (65 <= c) * (c <= 90) + (97 <= c) * (c <= 122) + (c == 95);
}

fn is_digit(c: i32) -> i32 {
    return (48 <= c) * (c <= 57);
}

fn is_ws(c: i32) -> i32 {
    return 0 < (c == 32) + (c == 10) + (c == 13) + (c == 9);
}

fn mem_eq(a: i32, b: i32, n: i32) -> i32 {
    let j: i32 = 0;
    while j < n {
        if load8(a + j) != load8(b + j) { return 0; }
        j = j + 1;
    }
    return 1;
}

fn kw_match(start: i32, len: i32, kw: i32) -> i32 {
    if mem_eq(start, kw, len) == 0 { return 0; }
    if load8(kw + len) == 0 { return 1; }
    return 0;
}

fn classify_ident(start: i32, len: i32) -> i32 {
    if kw_match(start, len, kw_fn) == 1 { return 10; }
    if kw_match(start, len, kw_let) == 1 { return 11; }
    if kw_match(start, len, kw_if) == 1 { return 12; }
    if kw_match(start, len, kw_else) == 1 { return 13; }
    if kw_match(start, len, kw_while) == 1 { return 14; }
    if kw_match(start, len, kw_return) == 1 { return 15; }
    if kw_match(start, len, kw_extern) == 1 { return 16; }
    if kw_match(start, len, kw_static) == 1 { return 17; }
    if kw_match(start, len, kw_for) == 1 { return 18; }
    if kw_match(start, len, kw_break) == 1 { return 19; }
    if kw_match(start, len, kw_continue) == 1 { return 20; }
    if kw_match(start, len, kw_struct) == 1 { return 21; }
    if kw_match(start, len, kw_new) == 1 { return 22; }
    return 1;
}

fn get16(a: i32) -> i32 {
    return load8(a) + load8(a + 1) * 256;
}

fn put16(a: i32, v: i32) -> i32 {
    store8(a, v % 256);
    store8(a + 1, v / 256);
    return 0;
}

fn get64(a: i32) -> i32 {
    let v: i32 = 0;
    let j: i32 = 8;
    while j > 0 {
        j = j - 1;
        v = v * 256 + load8(a + j);
    }
    return v;
}

fn put64(a: i32, v: i64) -> i32 {
    let x: i64 = v;
    let j: i32 = 0;
    while j < 8 {
        store8(a + j, x % 256);
        x = x / 256;
        j = j + 1;
    }
    return 0;
}

// token 回放：state 16 字节备份/恢复，实现单 token lookahead（intern 幂等，重放无害）
fn save_state() -> i32 {
    let j: i32 = 0;
    while j < 16 {
        store8(stbak + j, load8(state + j));
        j = j + 1;
    }
    return 0;
}

fn restore_state() -> i32 {
    let j: i32 = 0;
    while j < 16 {
        store8(state + j, load8(stbak + j));
        j = j + 1;
    }
    return 0;
}

fn intern(tab: i32, buf: i32, st: i32, len: i32) -> i32 {
    let count: i32 = get16(tab);
    let k: i32 = 0;
    while k < count {
        let e: i32 = tab + 4 + k * 4;
        if load8(e) == len {
            if mem_eq(buf + get16(e + 1), buf + st, len) == 1 {
                return k + 1;
            }
        }
        k = k + 1;
    }
    let e2: i32 = tab + 4 + count * 4;
    store8(e2, len);
    put16(e2 + 1, st);
    let nc: i32 = count + 1;
    put16(tab, nc);
    return nc;
}

fn slen(s: i32) -> i32 {
    let i: i32 = 0;
    while load8(s + i) != 0 { i = i + 1; }
    return i;
}

fn outs(s: i32) -> i32 {
    write(1, s, slen(s));
    return 0;
}

fn print_int(num: i32) -> i32 {
    if num == 0 {
        write(1, zero, 1);
        return 0;
    }
    let n: i32 = num;
    let idx: i32 = 12;
    while n > 0 {
        idx = idx - 1;
        let d: i32 = n % 10;
        store8(pbuf + idx, d + 48);
        n = n / 10;
    }
    write(1, pbuf + idx, 12 - idx);
    return 0;
}

fn out_name(tab: i32, buf: i32, sym: i32) -> i32 {
    let e: i32 = tab + 4 + (sym - 1) * 4;
    write(1, buf + get16(e + 1), load8(e));
    return 0;
}

fn cur_type() -> i32 {
    return load8(state + 2);
}

fn cur_val() -> i64 {
    return get64(state + 5);
}

fn cur_aux() -> i32 {
    return get16(state + 3);
}

fn parse_error() -> i32 {
    outs(s_errl);
    print_int(get16(curline));
    outs(s_tok);
    print_int(cur_type());
    outs(s_tok2);
    exit(1);
    return 0;
}

fn advance(buf: i32, len: i32, tab: i32) -> i32 {
    let pos: i32 = get16(state);
    let g: i32 = 0;
    let d: i32 = 0;
    let sk: i32 = 1;
    while sk == 1 {
        sk = 0;
        if pos < len {
            if is_ws(load8(buf + pos)) == 1 {
                if load8(buf + pos) == 10 { put16(curline, get16(curline) + 1); }
                pos = pos + 1;
                sk = 1;
            }
        }
        if sk == 0 {
            if pos + 1 < len {
                if (load8(buf + pos) == 47) * (load8(buf + pos + 1) == 47) == 1 {
                    g = 1;
                    while (g == 1) * (pos < len) == 1 {
                        if load8(buf + pos) == 10 {
                            put16(curline, get16(curline) + 1);
                            g = 0;
                        }
                        pos = pos + 1;
                    }
                    sk = 1;
                }
            }
        }
    }
    put16(tokpos, pos);
    let ty: i32 = 0;
    let aux: i32 = 0;
    let v64: i64 = 0;
    if pos < len {
        let c: i32 = load8(buf + pos);
        if is_digit(c) == 1 {
            ty = 2;
            if (c == 48) * (pos + 1 < len) * (load8(buf + pos + 1) == 120) == 1 {
                pos = pos + 2;
                g = 1;
                while (g == 1) * (pos < len) == 1 {
                    d = load8(buf + pos);
                    if is_digit(d) == 1 {
                        v64 = v64 * 16 + d - 48;
                        pos = pos + 1;
                    } else { if 0 < (97 <= d) * (d <= 102) {
                        v64 = v64 * 16 + d - 87;
                        pos = pos + 1;
                    } else { if 0 < (65 <= d) * (d <= 70) {
                        v64 = v64 * 16 + d - 55;
                        pos = pos + 1;
                    } else { g = 0; } } }
                }
            } else {
                g = 1;
                while (g == 1) * (pos < len) == 1 {
                    d = load8(buf + pos);
                    if is_digit(d) == 1 {
                        v64 = v64 * 10 + d - 48;
                        pos = pos + 1;
                    } else { g = 0; }
                }
            }
        } else { if is_alpha(c) == 1 {
            let st2: i32 = pos;
            g = 1;
            while (g == 1) * (pos < len) == 1 {
                d = load8(buf + pos);
                if 0 < is_alpha(d) + is_digit(d) { pos = pos + 1; } else { g = 0; }
            }
            ty = classify_ident(buf + st2, pos - st2);
            v64 = intern(tab, buf, st2, pos - st2);
        } else { if c == 34 {
            ty = 34;
            pos = pos + 1;
            aux = pos;
            g = 1;
            while (g == 1) * (pos < len) == 1 {
                d = load8(buf + pos);
                if d == 34 { g = 0; } else {
                    if d == 92 { pos = pos + 2; } else { pos = pos + 1; }
                }
            }
            v64 = pos - aux;
            pos = pos + 1;
        } else {
            ty = c;
            pos = pos + 1;
            if 0 < (c == 61) + (c == 33) + (c == 60) + (c == 62) {
                if pos < len {
                    if load8(buf + pos) == 61 {
                        if c == 61 { ty = 200; }
                        if c == 33 { ty = 201; }
                        if c == 60 { ty = 202; }
                        if c == 62 { ty = 203; }
                        pos = pos + 1;
                    }
                }
            }
            if ty == 60 {
                if pos < len {
                    if load8(buf + pos) == 60 { ty = 204; pos = pos + 1; }
                }
            }
            if ty == 62 {
                if pos < len {
                    if load8(buf + pos) == 62 { ty = 205; pos = pos + 1; }
                }
            }
        } } }
    }
    put16(state, pos);
    store8(state + 2, ty);
    put16(state + 3, aux);
    put64(state + 5, v64);
    return 0;
}

fn eat(buf: i32, len: i32, tab: i32, t: i32) -> i32 {
    if cur_type() != t { parse_error(); }
    advance(buf, len, tab);
    return 0;
}

fn next_label() -> i32 {
    let v: i32 = get16(lblc);
    put16(lblc, v + 1);
    return v;
}

// ---- 循环上下文栈（break/continue 目标标签）----
// loopstk[0..1]=深度；条目 d 在 2+d*6：[head][step][end]
// while 的 continue 目标 = head；for 的 continue 目标 = step 段

fn loop_push(h: i32, s: i32, e: i32) -> i32 {
    let d: i32 = get16(loopstk);
    if d == 8 { parse_error(); }
    let b: i32 = 2 + d * 6;
    put16(loopstk + b, h);
    put16(loopstk + b + 2, s);
    put16(loopstk + b + 4, e);
    put16(loopstk, d + 1);
    return 0;
}

fn loop_pop() -> i32 {
    put16(loopstk, get16(loopstk) - 1);
    return 0;
}

fn loop_step() -> i32 {
    let d: i32 = get16(loopstk);
    if d == 0 { parse_error(); }
    return get16(loopstk + 2 + (d - 1) * 6 + 2);
}

fn loop_end() -> i32 {
    let d: i32 = get16(loopstk);
    if d == 0 { parse_error(); }
    return get16(loopstk + 2 + (d - 1) * 6 + 4);
}

// ---- 三表（vtab / etab / stab 共居 tbl 块）----
// vtab 条目 4B = [sym16][flags16]，flags bit0 = owning（-manual 块尾自动 free）
//                                  flags bit1 = i64（原生 64 位槽位，走 x 寄存器全宽存取）

fn add_var(tbl: i32, sym: i32) -> i32 {
    let c: i32 = get16(tbl);
    if c == 16 { parse_error(); }
    put16(tbl + 2 + c * 4, sym);
    put16(tbl + 4 + c * 4, 0);
    put16(tbl, c + 1);
    return c + 1;
}

fn set_flags(tbl: i32, v: i32, f: i32) -> i32 {
    put16(tbl + 4 + (v - 1) * 4, f);
    return 0;
}

fn var_flag(tbl: i32, v: i32) -> i32 {
    return get16(tbl + 4 + (v - 1) * 4);
}

fn lookup_var(tbl: i32, sym: i32) -> i32 {
    let k: i32 = get16(tbl);
    while k > 0 {
        k = k - 1;
        if get16(tbl + 2 + k * 4) == sym { return k + 1; }
    }
    return 0;
}

fn add_ext(tbl: i32, sym: i32, kind: i32) -> i32 {
    let e: i32 = tbl + 256;
    let c: i32 = get16(e);
    put16(e + 2 + c * 4, sym);
    put16(e + 4 + c * 4, kind);
    put16(e, c + 1);
    return 0;
}

fn lookup_ext(tbl: i32, sym: i32) -> i32 {
    let e: i32 = tbl + 256;
    let c: i32 = get16(e);
    let k: i32 = 0;
    while k < c {
        if get16(e + 2 + k * 4) == sym { return get16(e + 4 + k * 4) + 1; }
        k = k + 1;
    }
    return 0;
}

fn add_static(tbl: i32, sym: i32) -> i32 {
    let e: i32 = tbl + 1024;
    let c: i32 = get16(e);
    put16(e + 2 + c * 2, sym);
    put16(e, c + 1);
    return c + 1;
}

fn lookup_static(tbl: i32, sym: i32) -> i32 {
    let e: i32 = tbl + 1024;
    let c: i32 = get16(e);
    let k: i32 = 0;
    while k < c {
        if get16(e + 2 + k * 2) == sym { return k + 1; }
        k = k + 1;
    }
    return 0;
}

fn sym_is(tab: i32, buf: i32, sym: i32, s: i32) -> i32 {
    let e: i32 = tab + 4 + (sym - 1) * 4;
    return kw_match(buf + get16(e + 1), load8(e), s);
}

// ---- sttab（结构体表 @ tbl+2048）----
// [+0]=条目数 [+2]=detail bump 指针（相对 +2048，起点 512）
// 条目 4B=[sym16][detail_off16]；detail=[size16][fcount16]+fcount*4B[sym16][off|wbit]

fn add_struct(tbl: i32, sym: i32, size: i32, fcount: i32) -> i32 {
    let b: i32 = tbl + 2048;
    let c: i32 = get16(b);
    let d: i32 = get16(b + 2);
    put16(b + 4 + c * 4, sym);
    put16(b + 6 + c * 4, d);
    put16(b + d, size);
    put16(b + d + 2, fcount);
    let j: i32 = 0;
    while j < fcount {
        put16(b + d + 4 + j * 4, get16(stmp + j * 4));
        put16(b + d + 6 + j * 4, get16(stmp + j * 4 + 2));
        j = j + 1;
    }
    put16(b + 2, d + 4 + fcount * 4);
    put16(b, c + 1);
    return c + 1;
}

fn lookup_struct(tbl: i32, sym: i32) -> i32 {
    let b: i32 = tbl + 2048;
    let c: i32 = get16(b);
    let k: i32 = 0;
    while k < c {
        if get16(b + 4 + k * 4) == sym { return k + 1; }
        k = k + 1;
    }
    return 0;
}

fn struct_detail(tbl: i32, idx: i32) -> i32 {
    return tbl + 2048 + get16(tbl + 2048 + 6 + (idx - 1) * 4);
}

fn struct_size(tbl: i32, idx: i32) -> i32 {
    return get16(struct_detail(tbl, idx));
}

fn struct_field(tbl: i32, idx: i32, fsym: i32) -> i32 {
    let d: i32 = struct_detail(tbl, idx);
    let fc: i32 = get16(d + 2);
    let k: i32 = 0;
    while k < fc {
        if get16(d + 4 + k * 4) == fsym {
            let ow: i32 = get16(d + 6 + k * 4);
            return (ow / 2) * 4 + ow % 2;
        }
        k = k + 1;
    }
    parse_error();
    return 0;
}

fn sys_kind(tab: i32, buf: i32, sym: i32) -> i32 {
    if sym_is(tab, buf, sym, n_exit) == 1 { return 1; }
    if sym_is(tab, buf, sym, n_read) == 1 { return 3; }
    if sym_is(tab, buf, sym, n_write) == 1 { return 4; }
    if sym_is(tab, buf, sym, n_open) == 1 { return 5; }
    if sym_is(tab, buf, sym, n_close) == 1 { return 6; }
    if sym_is(tab, buf, sym, n_load8) == 1 { return 4097; }
    if sym_is(tab, buf, sym, n_store8) == 1 { return 4098; }
    if sym_is(tab, buf, sym, n_mmap) == 1 { return 197; }
    if sym_is(tab, buf, sym, n_munmap) == 1 { return 73; }
    if sym_is(tab, buf, sym, n_load64) == 1 { return 4099; }
    if sym_is(tab, buf, sym, n_store64) == 1 { return 4100; }
    if sym_is(tab, buf, sym, n_load32) == 1 { return 4101; }
    if sym_is(tab, buf, sym, n_strlen) == 1 { return 8193; }
    if sym_is(tab, buf, sym, n_strappend) == 1 { return 8194; }
    if sym_is(tab, buf, sym, n_streq) == 1 { return 8195; }
    if sym_is(tab, buf, sym, n_strtoi) == 1 { return 8196; }
    return 65535;
}

// ---- 表达式代码生成（后缀流式，结果恒在 x0）----

fn gen_call(buf: i32, len: i32, tab: i32, tbl: i32, id: i32) -> i32 {
    advance(buf, len, tab);
    let argc: i32 = 0;
    if cur_type() != 41 {
        let go: i32 = 1;
        while go == 1 {
            gen_expr(buf, len, tab, tbl);
            outs(g_push);
            argc = argc + 1;
            if cur_type() == 44 { advance(buf, len, tab); } else { go = 0; }
        }
    }
    eat(buf, len, tab, 41);
    let k: i32 = argc;
    while k > 0 {
        k = k - 1;
        outs(g_popr);
        print_int(k);
        outs(g_popr2);
    }
    let kd: i32 = lookup_ext(tbl, id);
    if kd == 0 {
        outs(g_bl);
        out_name(tab, buf, id);
        outs(g_nl);
        return 0;
    }
    let kind: i32 = kd - 1;
    if kind == 0 {
        outs(g_bl);
        out_name(tab, buf, id);
        outs(g_nl);
        return 0;
    }
    if kind == 4097 { outs(g_ldrb); return 0; }
    if kind == 4098 { outs(g_strb); return 0; }
    if kind == 4099 { outs(g_ldr64); return 0; }
    if kind == 4100 { outs(g_str64); return 0; }
    if kind == 4101 { outs(g_ldr32); return 0; }
    if kind == 8193 {
        if get16(stdused) % 2 == 0 { put16(stdused, get16(stdused) + 1); }
        outs(g_bl);
        out_name(tab, buf, id);
        outs(g_nl);
        return 0;
    }
    if kind == 8194 {
        if get16(stdused) % 2 == 0 { put16(stdused, get16(stdused) + 1); }
        if (get16(stdused) / 2) % 2 == 0 { put16(stdused, get16(stdused) + 2); }
        outs(g_bl);
        out_name(tab, buf, id);
        outs(g_nl);
        return 0;
    }
    if kind == 8195 {
        if (get16(stdused) / 4) % 2 == 0 { put16(stdused, get16(stdused) + 4); }
        outs(g_bl);
        out_name(tab, buf, id);
        outs(g_nl);
        return 0;
    }
    if kind == 8196 {
        if (get16(stdused) / 8) % 2 == 0 { put16(stdused, get16(stdused) + 8); }
        outs(g_bl);
        out_name(tab, buf, id);
        outs(g_nl);
        return 0;
    }
    outs(g_svc1);
    print_int(kind);
    outs(g_nl);
    outs(g_svc2);
    return 0;
}

// 类型注解 -> vtab flags：i32->0 i64->2 struct->4+idx*16 [T;N]->8+wc*16
fn parse_type_info(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    if cur_type() == 91 {
        advance(buf, len, tab);
        let wc: i32 = 0;
        if sym_is(tab, buf, cur_val(), n_i64) == 1 { wc = 3; } else {
            if sym_is(tab, buf, cur_val(), n_i32) == 1 { wc = 2; } else { parse_error(); }
        }
        eat(buf, len, tab, 1);
        eat(buf, len, tab, 59);
        if cur_type() != 2 { parse_error(); }
        advance(buf, len, tab);
        eat(buf, len, tab, 93);
        return 8 + wc * 16;
    }
    if cur_type() != 1 { parse_error(); }
    if sym_is(tab, buf, cur_val(), n_i32) == 1 { advance(buf, len, tab); return 0; }
    if sym_is(tab, buf, cur_val(), n_i64) == 1 { advance(buf, len, tab); return 2; }
    let si: i32 = lookup_struct(tbl, cur_val());
    if si == 0 { parse_error(); }
    advance(buf, len, tab);
    return 4 + si * 16;
}

// new StructName / new [T; N]：编译期算 size，内联 bump 堆分配，结果在 x0
fn gen_new(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    advance(buf, len, tab);
    let size: i32 = 0;
    if cur_type() == 1 {
        let si: i32 = lookup_struct(tbl, cur_val());
        if si == 0 { parse_error(); }
        size = struct_size(tbl, si);
        eat(buf, len, tab, 1);
    } else {
        if cur_type() == 91 {
            advance(buf, len, tab);
            let w: i32 = 4;
            if sym_is(tab, buf, cur_val(), n_i64) == 1 { w = 8; } else {
                if sym_is(tab, buf, cur_val(), n_i32) == 0 { parse_error(); }
            }
            eat(buf, len, tab, 1);
            eat(buf, len, tab, 59);
            if cur_type() != 2 { parse_error(); }
            let n: i64 = cur_val();
            advance(buf, len, tab);
            eat(buf, len, tab, 93);
            size = n * w;
        } else { parse_error(); }
    }
    outs(g_heap_adr);
    outs(g_heap_ld);
    outs(g_heap_mv);
    print_int(size);
    outs(g_heap_bmp);
    return 0;
}

// 后缀链：'.' 字段 / '[' 下标'，基址恒在 x0
// mode=0 收尾按宽度 load；mode=1 留地址（左值用）；返回 宽度*2+宽度位
fn gen_postfix(buf: i32, len: i32, tab: i32, tbl: i32, kind: i32, pl: i32, mode: i32) -> i32 {
    let width: i32 = 8;
    while 0 < (cur_type() == 46) + (cur_type() == 91) {
        if kind == 1 {
            if cur_type() != 46 { parse_error(); }
            advance(buf, len, tab);
            let fsym: i32 = cur_val();
            eat(buf, len, tab, 1);
            let r: i32 = struct_field(tbl, pl, fsym);
            outs(g_addimm);
            print_int(r / 2);
            outs(g_nl);
            if r % 2 == 1 { width = 8; } else { width = 4; }
            kind = 0;
        } else {
            if kind == 2 {
                if cur_type() != 91 { parse_error(); }
                advance(buf, len, tab);
                outs(g_push);
                gen_expr(buf, len, tab, tbl);
                outs(g_pop9);
                outs(g_lslimm);
                print_int(pl);
                outs(g_nl);
                outs(g_add);
                eat(buf, len, tab, 93);
                if pl == 3 { width = 8; } else { width = 4; }
                kind = 0;
            } else { parse_error(); }
        }
    }
    if mode == 0 {
        if width == 8 { outs(g_ldr64); } else { outs(g_ldr32); }
    }
    return width * 2 + width / 8;
}

fn gen_factor(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    let ty: i32 = cur_type();
    if ty == 126 {
        advance(buf, len, tab);
        gen_factor(buf, len, tab, tbl);
        outs(g_mvn);
        return 0;
    }
    if ty == 2 {
        let n: i64 = cur_val();
        if n <= 65535 {
            outs(g_movx0);
            print_int(n);
            outs(g_nl);
        } else {
            outs(g_movz);
            print_int(n % (65535 + 1));
            outs(g_nl);
            let sh: i32 = 16;
            let m: i64 = n / (65535 + 1);
            while m > 0 {
                outs(g_movk);
                print_int(m % (65535 + 1));
                outs(g_lslt);
                print_int(sh);
                outs(g_nl);
                m = m / (65535 + 1);
                sh = sh + 16;
            }
        }
        advance(buf, len, tab);
        return 0;
    }
    if ty == 34 {
        let ln: i32 = get16(litc);
        put16(litc, ln + 1);
        outs(g_lit1);
        print_int(ln);
        outs(g_lit2);
        write(1, buf + cur_aux(), cur_val());
        outs(g_d3);
        outs(g_litadr1);
        print_int(ln);
        outs(g_litadr2);
        print_int(ln);
        outs(g_adrp3);
        advance(buf, len, tab);
        return 0;
    }
    if ty == 22 {
        return gen_new(buf, len, tab, tbl);
    }
    if ty == 1 {
        let id: i32 = cur_val();
        advance(buf, len, tab);
        if cur_type() == 40 {
            gen_call(buf, len, tab, tbl, id);
            return 0;
        }
        let v: i32 = lookup_var(tbl, id);
        if v > 0 {
            let vf: i32 = var_flag(tbl, v);
            if vf >= 2 { outs(g_ldr1x); } else { outs(g_ldr1); }
            print_int(v * 8);
            outs(g_close);
            if 0 < (cur_type() == 46) + (cur_type() == 91) {
                gen_postfix(buf, len, tab, tbl, (vf / 4) % 4, vf / 16, 0);
            }
            return 0;
        }
        let s: i32 = lookup_static(tbl, id);
        if s > 0 {
            outs(g_adrp1);
            print_int(s - 1);
            outs(g_adrp2);
            print_int(s - 1);
            outs(g_adrp3);
            return 0;
        }
        parse_error();
    }
    if ty == 40 {
        advance(buf, len, tab);
        gen_expr(buf, len, tab, tbl);
        eat(buf, len, tab, 41);
        return 0;
    }
    parse_error();
    return 0;
}

fn gen_term(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    gen_factor(buf, len, tab, tbl);
    let go: i32 = 1;
    while go == 1 {
        let ty: i32 = cur_type();
        if 0 < (ty == 42) + (ty == 47) + (ty == 37) {
            outs(g_push);
            advance(buf, len, tab);
            gen_factor(buf, len, tab, tbl);
            outs(g_pop9);
            if ty == 42 { outs(g_mul); }
            if ty == 47 { outs(g_div); }
            if ty == 37 { outs(g_mod); }
        } else { go = 0; }
    }
    return 0;
}

fn gen_add(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    gen_term(buf, len, tab, tbl);
    let go: i32 = 1;
    while go == 1 {
        let ty: i32 = cur_type();
        if 0 < (ty == 43) + (ty == 45) {
            outs(g_push);
            advance(buf, len, tab);
            gen_term(buf, len, tab, tbl);
            outs(g_pop9);
            if ty == 43 { outs(g_add); }
            if ty == 45 { outs(g_sub); }
        } else { go = 0; }
    }
    return 0;
}

// 优先级链（C 序）：factor(~) -> term(* / %) -> add(+ -) -> shift(<< >>)
//   -> cmp(比较，非结合) -> band(&) -> bxor(^) -> bor(|) = gen_expr
fn gen_shift(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    gen_add(buf, len, tab, tbl);
    let go: i32 = 1;
    while go == 1 {
        let ty: i32 = cur_type();
        if 0 < (ty == 204) + (ty == 205) {
            outs(g_push);
            advance(buf, len, tab);
            gen_add(buf, len, tab, tbl);
            outs(g_pop9);
            if ty == 204 { outs(g_lsl); }
            if ty == 205 { outs(g_lsr); }
        } else { go = 0; }
    }
    return 0;
}

fn gen_cmp(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    gen_shift(buf, len, tab, tbl);
    let ty: i32 = cur_type();
    if 0 < (ty == 60) + (ty == 62) + (ty == 200) + (ty == 201) + (ty == 202) + (ty == 203) {
        outs(g_push);
        advance(buf, len, tab);
        gen_shift(buf, len, tab, tbl);
        outs(g_pop9);
        outs(g_cmp);
        if ty == 200 { outs(c_eq); }
        if ty == 201 { outs(c_ne); }
        if ty == 60 { outs(c_lt); }
        if ty == 62 { outs(c_gt); }
        if ty == 202 { outs(c_le); }
        if ty == 203 { outs(c_ge); }
    }
    return 0;
}

fn gen_band(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    gen_cmp(buf, len, tab, tbl);
    let go: i32 = 1;
    while go == 1 {
        if cur_type() == 38 {
            outs(g_push);
            advance(buf, len, tab);
            gen_cmp(buf, len, tab, tbl);
            outs(g_pop9);
            outs(g_and);
        } else { go = 0; }
    }
    return 0;
}

fn gen_bxor(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    gen_band(buf, len, tab, tbl);
    let go: i32 = 1;
    while go == 1 {
        if cur_type() == 94 {
            outs(g_push);
            advance(buf, len, tab);
            gen_band(buf, len, tab, tbl);
            outs(g_pop9);
            outs(g_eor);
        } else { go = 0; }
    }
    return 0;
}

fn gen_expr(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    gen_bxor(buf, len, tab, tbl);
    let go: i32 = 1;
    while go == 1 {
        if cur_type() == 124 {
            outs(g_push);
            advance(buf, len, tab);
            gen_bxor(buf, len, tab, tbl);
            outs(g_pop9);
            outs(g_orr);
        } else { go = 0; }
    }
    return 0;
}

// ---- 语句代码生成 ----

// 统一尾声：-manual 先 free 本函数 owning 槽（skip 豁免逃逸槽），
// -gc 注销根帧；x0 经 sp 栈保护穿越运行时调用
fn gen_epi_seq(tbl: i32, skip: i32) -> i32 {
    let m: i32 = get16(modes);
    if m == 1 {
        let c: i32 = get16(tbl);
        let any: i32 = 0;
        let k: i32 = 0;
        while k < c {
            if var_flag(tbl, k + 1) % 2 == 1 {
                if k + 1 != skip { any = any + 1; }
            }
            k = k + 1;
        }
        if any > 0 {
            outs(g_push);
            k = 0;
            while k < c {
                if var_flag(tbl, k + 1) % 2 == 1 {
                    if k + 1 != skip {
                        outs(g_ldr1);
                        print_int((k + 1) * 8);
                        outs(g_close);
                        outs(g_rtfree);
                    }
                }
                k = k + 1;
            }
            outs(g_pop0);
        }
    }
    if m == 2 {
        outs(g_push);
        outs(g_gcpop);
        outs(g_pop0);
    }
    outs(g_epi);
    return 0;
}

// return 语句（'return' 已消费）：纯变量 return 用 lookahead 豁免该槽的 free
fn gen_return(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    let rid: i32 = 0;
    if cur_type() == 59 {
        outs(g_zero);
    } else {
        if cur_type() == 1 {
            save_state();
            let idt: i32 = cur_val();
            advance(buf, len, tab);
            if cur_type() == 59 {
                let vv: i32 = lookup_var(tbl, idt);
                if vv > 0 { rid = vv; }
            }
            restore_state();
        }
        gen_expr(buf, len, tab, tbl);
    }
    gen_epi_seq(tbl, rid);
    eat(buf, len, tab, 59);
    return 0;
}

// for init; cond; step { body }
// 流式展开：init → L(head): cond cbz L(end) → body → L(step): step → b L(head) → L(end):
// step 在源码里位于 body 之前，但代码必须落在 body 之后：
// 先词法跳过 step 记住起止位置，发射完 body 后回卷游标重放 gen_stmt 发射 step。
fn gen_for(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    advance(buf, len, tab);
    gen_stmt(buf, len, tab, tbl);
    let lh: i32 = next_label();
    let ls: i32 = next_label();
    let le: i32 = next_label();
    loop_push(lh, ls, le);
    outs(g_L);
    print_int(lh);
    outs(g_colon);
    gen_expr(buf, len, tab, tbl);
    eat(buf, len, tab, 59);
    outs(g_cbz);
    print_int(le);
    outs(g_nl);
    let p1: i32 = get16(tokpos);
    let go: i32 = 1;
    while (go == 1) * (cur_type() != 0) == 1 {
        if cur_type() == 59 { go = 0; } else { advance(buf, len, tab); }
    }
    if cur_type() != 59 { parse_error(); }
    advance(buf, len, tab);
    gen_block(buf, len, tab, tbl);
    let p3: i32 = get16(tokpos);
    put16(state, p1);
    advance(buf, len, tab);
    outs(g_L);
    print_int(ls);
    outs(g_colon);
    gen_stmt(buf, len, tab, tbl);
    put16(state, p3);
    advance(buf, len, tab);
    outs(g_b);
    print_int(lh);
    outs(g_nl);
    outs(g_L);
    print_int(le);
    outs(g_colon);
    loop_pop();
    return 0;
}

fn gen_block(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    eat(buf, len, tab, 123);
    let last: i32 = 0;
    while (cur_type() != 125) * (cur_type() != 0) == 1 {
        last = gen_stmt(buf, len, tab, tbl);
    }
    eat(buf, len, tab, 125);
    return last;
}

// 左值赋值：id 已消费，'.'/ '[' 打头；算地址留 x0，再按宽度 store
fn gen_lvalue(buf: i32, len: i32, tab: i32, tbl: i32, id: i32) -> i32 {
    let v3: i32 = lookup_var(tbl, id);
    if v3 == 0 { parse_error(); }
    let vf3: i32 = var_flag(tbl, v3);
    if vf3 < 4 { parse_error(); }
    outs(g_ldr1x);
    print_int(v3 * 8);
    outs(g_close);
    let r3: i32 = gen_postfix(buf, len, tab, tbl, (vf3 / 4) % 4, vf3 / 16, 1);
    eat(buf, len, tab, 61);
    outs(g_push);
    gen_expr(buf, len, tab, tbl);
    outs(g_pop9);
    if r3 % 2 == 1 { outs(g_stx9); } else { outs(g_stw9); }
    eat(buf, len, tab, 59);
    return 0;
}

fn gen_stmt(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    let ty: i32 = cur_type();
    if ty == 11 {
        advance(buf, len, tab);
        let name: i32 = cur_val();
        eat(buf, len, tab, 1);
        eat(buf, len, tab, 58);
        let tf: i32 = parse_type_info(buf, len, tab, tbl);
        eat(buf, len, tab, 61);
        let own: i32 = 0;
        if get16(modes) == 1 {
            if cur_type() == 1 {
                if sym_is(tab, buf, cur_val(), n_alloc) == 1 { own = 1; }
            }
        }
        gen_expr(buf, len, tab, tbl);
        let v: i32 = add_var(tbl, name);
        set_flags(tbl, v, tf + own);
        if tf >= 2 { outs(g_str1x); } else { outs(g_str1); }
        print_int(v * 8);
        outs(g_close);
        eat(buf, len, tab, 59);
        return 0;
    }
    if ty == 12 {
        advance(buf, len, tab);
        gen_expr(buf, len, tab, tbl);
        let l: i32 = next_label();
        outs(g_cbz);
        print_int(l);
        outs(g_nl);
        gen_block(buf, len, tab, tbl);
        if cur_type() == 13 {
            advance(buf, len, tab);
            let l2: i32 = next_label();
            outs(g_b);
            print_int(l2);
            outs(g_nl);
            outs(g_L);
            print_int(l);
            outs(g_colon);
            gen_block(buf, len, tab, tbl);
            outs(g_L);
            print_int(l2);
            outs(g_colon);
        } else {
            outs(g_L);
            print_int(l);
            outs(g_colon);
        }
        return 0;
    }
    if ty == 14 {
        advance(buf, len, tab);
        let lw: i32 = next_label();
        let le: i32 = next_label();
        loop_push(lw, lw, le);
        outs(g_L);
        print_int(lw);
        outs(g_colon);
        gen_expr(buf, len, tab, tbl);
        outs(g_cbz);
        print_int(le);
        outs(g_nl);
        gen_block(buf, len, tab, tbl);
        outs(g_b);
        print_int(lw);
        outs(g_nl);
        outs(g_L);
        print_int(le);
        outs(g_colon);
        loop_pop();
        return 0;
    }
    if ty == 18 {
        return gen_for(buf, len, tab, tbl);
    }
    if ty == 19 {
        advance(buf, len, tab);
        outs(g_b);
        print_int(loop_end());
        outs(g_nl);
        eat(buf, len, tab, 59);
        return 0;
    }
    if ty == 20 {
        advance(buf, len, tab);
        outs(g_b);
        print_int(loop_step());
        outs(g_nl);
        eat(buf, len, tab, 59);
        return 0;
    }
    if ty == 15 {
        advance(buf, len, tab);
        gen_return(buf, len, tab, tbl);
        return 15;
    }
    if ty == 1 {
        let id: i32 = cur_val();
        advance(buf, len, tab);
        if cur_type() == 61 {
            advance(buf, len, tab);
            gen_expr(buf, len, tab, tbl);
            let v2: i32 = lookup_var(tbl, id);
            if v2 == 0 { parse_error(); }
            if var_flag(tbl, v2) >= 2 { outs(g_str1x); } else { outs(g_str1); }
            print_int(v2 * 8);
            outs(g_close);
            eat(buf, len, tab, 59);
            return 0;
        }
        if 0 < (cur_type() == 46) + (cur_type() == 91) {
            return gen_lvalue(buf, len, tab, tbl, id);
        }
        if cur_type() == 40 {
            gen_call(buf, len, tab, tbl, id);
            eat(buf, len, tab, 59);
            return 0;
        }
        parse_error();
    }
    if ty == 123 {
        gen_block(buf, len, tab, tbl);
        return 0;
    }
    parse_error();
    return 0;
}

// ---- 顶层声明 ----

fn gen_params(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    let argc: i32 = 0;
    if cur_type() == 1 {
        let go: i32 = 1;
        while go == 1 {
            let pv: i32 = add_var(tbl, cur_val());
            eat(buf, len, tab, 1);
            eat(buf, len, tab, 58);
            set_flags(tbl, pv, parse_type_info(buf, len, tab, tbl));
            argc = argc + 1;
            if cur_type() == 44 { advance(buf, len, tab); } else { go = 0; }
        }
    }
    return argc;
}

fn gen_fn(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    eat(buf, len, tab, 10);
    let name: i32 = cur_val();
    eat(buf, len, tab, 1);
    put16(tbl, 0);
    eat(buf, len, tab, 40);
    let argc: i32 = gen_params(buf, len, tab, tbl);
    eat(buf, len, tab, 41);
    if cur_type() == 45 {
        advance(buf, len, tab);
        eat(buf, len, tab, 62);
        eat(buf, len, tab, 1);
    }
    outs(g_fn1);
    out_name(tab, buf, name);
    outs(g_us);
    out_name(tab, buf, name);
    outs(g_fn2);
    if get16(modes) == 2 {
        let z: i32 = 16;                // -gc：帧清零（杆掉保守扫描的栈残渣假阳性）
        while z <= 128 {
            outs(g_z1);
            print_int(z);
            outs(g_close);
            z = z + 16;
        }
    }
    let i: i32 = 0;
    while i < argc {
        outs(g_par1);
        print_int(i);
        outs(g_par2);
        print_int(8 + i * 8);
        outs(g_close);
        i = i + 1;
    }
    if get16(modes) == 2 { outs(g_gcpush); }    // 参数入槽后注册根帧（bl 毁 x0-x7）
    let last: i32 = gen_block(buf, len, tab, tbl);
    if last != 15 {                             // 末语句非 return 才需兜底尾声（死代码消除）
        outs(g_zero);
        gen_epi_seq(tbl, 0);
    }
    return 0;
}

fn gen_extern(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    eat(buf, len, tab, 16);
    let isc: i32 = 0;
    if cur_type() == 34 {
        isc = 1;
        advance(buf, len, tab);
    }
    eat(buf, len, tab, 10);
    let name: i32 = cur_val();
    eat(buf, len, tab, 1);
    put16(tbl, 0);
    eat(buf, len, tab, 40);
    gen_params(buf, len, tab, tbl);
    eat(buf, len, tab, 41);
    if cur_type() == 45 {
        advance(buf, len, tab);
        eat(buf, len, tab, 62);
        eat(buf, len, tab, 1);
    }
    let kind: i32 = 0;
    if isc == 0 {
        kind = sys_kind(tab, buf, name);
        if kind == 65535 { parse_error(); }
    }
    add_ext(tbl, name, kind);
    eat(buf, len, tab, 59);
    return 0;
}

fn gen_static(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    eat(buf, len, tab, 17);
    let name: i32 = cur_val();
    eat(buf, len, tab, 1);
    eat(buf, len, tab, 58);
    eat(buf, len, tab, 91);
    eat(buf, len, tab, 1);
    eat(buf, len, tab, 93);
    eat(buf, len, tab, 61);
    if cur_type() != 34 { parse_error(); }
    let sn: i32 = add_static(tbl, name);
    outs(g_d1);
    print_int(sn - 1);
    outs(g_d2);
    write(1, buf + cur_aux(), cur_val());
    outs(g_d3);
    advance(buf, len, tab);
    eat(buf, len, tab, 59);
    return 0;
}

// struct Name { f1: i32, f2: i64, ... }：偏移/大小自动计算，登记 sttab
fn gen_struct(buf: i32, len: i32, tab: i32, tbl: i32) -> i32 {
    eat(buf, len, tab, 21);
    let name: i32 = cur_val();
    eat(buf, len, tab, 1);
    if lookup_struct(tbl, name) != 0 { parse_error(); }
    eat(buf, len, tab, 123);
    if cur_type() == 125 { parse_error(); }
    let off: i32 = 0;
    let fc: i32 = 0;
    let go: i32 = 1;
    while go == 1 {
        let fsym: i32 = cur_val();
        eat(buf, len, tab, 1);
        eat(buf, len, tab, 58);
        let w: i32 = 4;
        let wb: i32 = 0;
        if sym_is(tab, buf, cur_val(), n_i64) == 1 { w = 8; wb = 1; } else {
            if sym_is(tab, buf, cur_val(), n_i32) == 0 { parse_error(); }
        }
        eat(buf, len, tab, 1);
        if w == 8 { off = (off + 7) / 8 * 8; }
        put16(stmp + fc * 4, fsym);
        put16(stmp + fc * 4 + 2, off + wb);
        fc = fc + 1;
        off = off + w;
        if cur_type() == 44 { advance(buf, len, tab); } else { go = 0; }
    }
    eat(buf, len, tab, 125);
    off = (off + 7) / 8 * 8;
    add_struct(tbl, name, off, fc);
    return 0;
}

fn main(argc: i32, argv: i32) -> i32 {
    put16(modes, 0);
    if argc > 1 {
        let a1: i32 = get64(argv + 8);
        if kw_match(a1, slen(a1), f_manual) == 1 { put16(modes, 1); }
        if kw_match(a1, slen(a1), f_gc) == 1 { put16(modes, 2); }
    }
    let pool: i32 = hf_asm_pool_create(65535 + 1, 3);
    if pool == 0 { return 255; }
    let buf: i32 = hf_asm_pool_alloc(pool);
    let tab: i32 = hf_asm_pool_alloc(pool);
    let tbl: i32 = hf_asm_pool_alloc(pool);
    if tbl == 0 { return 254; }
    put16(tab, 0);
    put16(tbl, 0);
    put16(tbl + 256, 0);
    put16(tbl + 1024, 0);
    put16(tbl + 2048, 0);
    put16(tbl + 2050, 512);
    put16(lblc, 0);
    put16(loopstk, 0);
    put16(stdused, 0);
    put16(litc, 0);
    let fd: i32 = open(path, 0);
    if fd < 3 { return 253; }
    let len: i32 = read(fd, buf, 65535);
    close(fd);

    outs(g_head);
    outs(g_heap_data);
    put16(state, 0);
    put16(curline, 1);
    advance(buf, len, tab);
    let go: i32 = 1;
    while go == 1 {
        let t: i32 = cur_type();
        if t == 0 { go = 0; } else {
            if t == 16 { gen_extern(buf, len, tab, tbl); } else {
                if t == 17 { gen_static(buf, len, tab, tbl); } else {
                    if t == 21 { gen_struct(buf, len, tab, tbl); } else {
                        if t == 10 { gen_fn(buf, len, tab, tbl); } else {
                            parse_error();
                        }
                    }
                }
            }
        }
    }

    if get16(stdused) % 2 == 1 { outs(s_strlen); }
    if (get16(stdused) / 2) % 2 == 1 { outs(s_strappend); }
    if (get16(stdused) / 4) % 2 == 1 { outs(s_streq); }
    if (get16(stdused) / 8) % 2 == 1 { outs(s_strtoi); }

    hf_asm_pool_destroy(pool);
    return 0;
}
